"""init table

Revision ID: 77ea0fe08343
Revises: 
Create Date: 2026-08-16 22:09:16.305603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77ea0fe08343'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_dashboard_daily_trends',
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('execution_total', sa.Integer(), nullable=False),
    sa.Column('success_cases', sa.Integer(), nullable=False),
    sa.Column('failure_cases', sa.Integer(), nullable=False),
    sa.Column('skipped_cases', sa.Integer(), nullable=False),
    sa.Column('running_cases', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('stat_date')
    )
    op.create_table('automation_dashboard_execution_item_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('case_key', sa.String(length=512), nullable=False),
    sa.Column('case_name', sa.String(length=255), nullable=False),
    sa.Column('attempt_number', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', 'case_key', name='uq_automation_dashboard_execution_item_snapshots_case')
    )
    op.create_index('idx_automation_dashboard_execution_item_snapshots_execution', 'automation_dashboard_execution_item_snapshots', ['execution_id', 'start_time'], unique=False)
    op.create_table('automation_dashboard_execution_snapshots',
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('job_url', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('pre_cases_count', sa.Integer(), nullable=False),
    sa.Column('completed_cases_count', sa.Integer(), nullable=False),
    sa.Column('success_cases_count', sa.Integer(), nullable=False),
    sa.Column('failure_cases_count', sa.Integer(), nullable=False),
    sa.Column('skipped_cases_count', sa.Integer(), nullable=False),
    sa.Column('running_cases_count', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('running_case_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index('idx_automation_dashboard_execution_snapshots_status', 'automation_dashboard_execution_snapshots', ['status', 'start_time'], unique=False)
    op.create_table('automation_dashboard_summary_snapshots',
    sa.Column('snapshot_key', sa.String(length=32), nullable=False),
    sa.Column('active_jobs_count', sa.Integer(), nullable=False),
    sa.Column('total_executions_count', sa.Integer(), nullable=False),
    sa.Column('running_executions_count', sa.Integer(), nullable=False),
    sa.Column('success_cases_7d', sa.Integer(), nullable=False),
    sa.Column('failure_cases_7d', sa.Integer(), nullable=False),
    sa.Column('skipped_cases_7d', sa.Integer(), nullable=False),
    sa.Column('pass_rate_7d', sa.Float(), nullable=False),
    sa.Column('avg_execution_duration_7d', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_key')
    )
    op.create_table('execution_case_step_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('attachment_type', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_item_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_uid', sa.UUID(), nullable=False),
    sa.Column('parent_step_id', sa.Integer(), nullable=True),
    sa.Column('parent_step_index', sa.Integer(), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_path', sa.String(length=255), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_uid', 'step_path', name='uq_execution_item_steps_path')
    )
    op.create_index('idx_execution_item_steps_case_parent', 'execution_item_steps', ['case_uid', 'parent_step_id'], unique=False)
    op.create_index('idx_execution_item_steps_case_path', 'execution_item_steps', ['case_uid', 'step_path'], unique=False)
    op.create_table('execution_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('build_uid', sa.UUID(), nullable=False),
    sa.Column('case_uid', sa.UUID(), nullable=False),
    sa.Column('case_key', sa.String(length=128), nullable=False),
    sa.Column('case_name', sa.Text(), nullable=False),
    sa.Column('labels', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('attempt_number', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('is_latest', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_uid', 'case_key', 'attempt_number', name='uq_execution_items_attempt'),
    sa.UniqueConstraint('case_uid')
    )
    op.create_table('jenkins_pipelines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('job_url', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_build_number', sa.Integer(), nullable=True),
    sa.Column('last_build_uid', sa.UUID(), nullable=True),
    sa.Column('last_build_status', sa.String(length=32), nullable=True),
    sa.Column('last_build_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_build_duration', sa.Float(), nullable=True),
    sa.Column('pipeline_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sync_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name'),
    sa.UniqueConstraint('last_build_uid')
    )
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('resource_type IN (1, 2, 3)', name='chk_permissions_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sys_dict',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dict_type', sa.String(length=64), nullable=False),
    sa.Column('code', sa.SmallInteger(), nullable=False, comment='字典编码'),
    sa.Column('label', sa.String(length=128), nullable=False, comment='前端标签'),
    sa.Column('dict_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True, comment='字典分类'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('color', sa.String(length=32), nullable=True, comment='前端颜色'),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dict_type'),
    sa.UniqueConstraint('dict_type', 'code', name='uq_sys_dict_type_code')
    )
    op.create_index('idx_sys_dict_type', 'sys_dict', ['dict_type'], unique=False)
    op.create_table('test_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('build_uid', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('job_url', sa.String(length=255), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('software_name', sa.String(length=100), nullable=False),
    sa.Column('software_version', sa.String(length=100), nullable=False),
    sa.Column('labels', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('planned_cases_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pass_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failure_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pass_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_uid')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Primary Key'),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User Email'),
    sa.Column('password_hash', sa.Text(), nullable=False, comment='Password Hash'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='Status'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Last Login Time'),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True, comment='Last Login IP'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('status IN (0, 1, 2)', name='chk_users_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_role_permissions_perm_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_roles_role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('idx_role_permissions_perm_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('test_executions')
    op.drop_index('idx_sys_dict_type', table_name='sys_dict')
    op.drop_table('sys_dict')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('jenkins_pipelines')
    op.drop_table('execution_items')
    op.drop_index('idx_execution_item_steps_case_path', table_name='execution_item_steps')
    op.drop_index('idx_execution_item_steps_case_parent', table_name='execution_item_steps')
    op.drop_table('execution_item_steps')
    op.drop_table('execution_case_step_attachments')
    op.drop_table('automation_dashboard_summary_snapshots')
    op.drop_index('idx_automation_dashboard_execution_snapshots_status', table_name='automation_dashboard_execution_snapshots')
    op.drop_table('automation_dashboard_execution_snapshots')
    op.drop_index('idx_automation_dashboard_execution_item_snapshots_execution', table_name='automation_dashboard_execution_item_snapshots')
    op.drop_table('automation_dashboard_execution_item_snapshots')
    op.drop_table('automation_dashboard_daily_trends')
    # ### end Alembic commands ###
